services:
  one:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - "storage:/usr/local/apache2/htdocs"

  two:
    image: httpd
    ports:
      - "90:80"
    volumes:
      - "storage1:/usr/local/apache2/htdocs"

  three:
    image: httpd
    ports:
      - "95:80"
    volumes:
      - "storage2:/usr/local/apache2/htdocs"

volumes:
  storage:
  storage1:
  storage2: