services:
  one:
    image: httpd
    ports:
      - "80:80"
    volumes:
      - "storage:/usr/local/apache2/htdocs"
    networks:
      - "test"

  two:
    image: httpd
    ports:
      - "90:80"
    volumes:
      - "storage1:/usr/local/apache2/htdocs"
    networks:
      - "test"

  three:
    image: httpd
    ports:
      - "96:80"
    volumes:
      - "storage2:/usr/local/apache2/htdocs"
    networks:
      - "test"

volumes:
  storage:
    external: true
  storage1:
    external: true
  storage2:
    external: true

networks:
  test:
    driver: bridge

